# Use an official Node.js runtime as a parent image
FROM node:25-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port your app runs on (internal to the container)
EXPOSE 8001

# Define the command to run your app
CMD ["node", "server.js"]
